ALTER TABLE users MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE exercises MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE workouts MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE workouts MODIFY COLUMN user_id BIGINT NOT NULL;

ALTER TABLE workout_exercises MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE workout_exercises MODIFY COLUMN workout_id BIGINT NOT NULL;
ALTER TABLE workout_exercises MODIFY COLUMN exercise_id BIGINT NOT NULL;